version: "4.0"

services:
  redis:
    container_name: redis
    image: "redis:alpine"
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./init-mongodb:/docker-entrypoint-initdb.d
      - ./init-mongodb/data:/tmp/data
  web:
    build: .
    container_name: ${COMPOSE_PROJECT_NAME}
    restart: always
    environment:
      TZ: Asia/Shanghai
      mongo.host: mongo
      mongo.username: root
      mongo.password: root
      mongo.database: data-jelly-fish
      redis.host: redis
    image: data-jelly-fish
    ports:
      - "8080:8080"
