

pac4j:
  callbackUrl: http://localhost:8080/callback
  logout:
    defaultUrl: http://localhost:8080/view/admin
    localLogout: true
  # Put all parameters under `properties`
  # Check supported sso config parameters for different authentication clients from the below link
  # https://github.com/pac4j/pac4j/blob/master/documentation/docs/config-module.md
  properties:
    usernameAttribute: username
    nicknameAttribute: username
    # Optional, change by authentication client
    # Please replace and fill in your client config below when enabled SSO
    formClient.loginUrl: /login
    formClient.authenticator: testUsernamePassword